<e> ::= <slot><slot><anygate><slot><slot>
<anygate> ::=  <anygate><anygate> | name(<slots>) | name(<slots>) name(<slots>) | name(<slots>) | name(<slots>) | {<event>} | {<event>} | {<event>} | {<event>} | {<event>} | {<event>} | {<event>} | {<event>}
<slot> ::= <anygate> | '' | '' | '' | '' | '' | '' | '' | '' | ''
<slots> ::= <slot><slot><anygate><slot><slot>

<d> ::= d
<r> ::= r
<q> ::= q
<t> ::= t
<{> ::= {

name ::= and | xor | seq | opt | lo<0_n>
<empty> ::= <empty2>
<empty2> ::= ''

<event> ::= GE_RANGE:dataset_vars

<0_n> ::= GE_RANGE:3