<e> ::= <somethingnoseq>

<somethingnoseq> ::= <somethingnoseq><somethingnoseq> | <andgate> | {<process>}

<something> ::=  <something><something> | <andgate> | <seqgate> | {<process>}

<andgate> ::= and(<something><something>)

<seqgate> ::= seq(<somethingnoseq><somethingnoseq>)

<process> ::= a | b | c | d | e | f