<e> ::= <slot><slot><anygate><slot><slot>
<anygate> ::=  <anygate><anygate> | <name>(<slots>) | {<event>}
<slot> ::= <anygate> | <empty> | <empty> | <empty> | <empty> | <empty> | <empty> | <empty> | <empty> | <empty>
<slots> ::= <slot><slot><anygate><slot><slot>

<name> ::= an<d> | xo<r>  | se<q> | op<t> | lo<0_n>

<d> ::= d
<r> ::= r
<q> ::= q
<t> ::= t
<{> ::= {
<empty> ::= <empty2>
<empty2> ::= ''

<event> ::= GE_RANGE:dataset_vars

<0_n> ::= GE_RANGE:5