<e> ::= <notallowstartingwithtrm>

<somethingnoseq> ::= <somethingnoseq><somethingnoseq> | <andgate> | <xorgate> | <optgate> | <lopgate> | <terminate> | {<process>}

<something> ::=  <something><something> | <andgate> | <xorgate> | <seqgate> | <optgate> | <lopgate> | {<process>}

<andgate> ::= and(<something><something>)

<xorgate> ::= xor(<something><something>)

<seqgate> ::= seq(<somethingnoseq><somethingnoseq>)

<optgate> ::= opt(<somethingnosingleopt>)

<optdoublegate> ::= opt(<something><something>)

<somethingnosingleopt> ::=<something><something> | <andgate> | <xorgate> | <seqgate> | <lopgate> | {<process>}

<lopgate> ::= lop(<somethingnosinglelop>)

<somethingnosinglelop> ::= <somethingnoseq><somethingnoseq> | <andgate> | <xorgate> | <seqgate> | <optdoublegate> | {<process>}

<terminate> ::= trm()

<notallowstartingwithtrm> ::= <notallowstartingwithtrm><somethingnoseq> | <andgate> | <xorgate> | <optgate> | <lopgate> | {<process>}

<process> ::= a | b | c | d