<e> ::= <something>

<something> ::=  <something><something> | <andgate> | <xorgate> | <seqgate> | <optgate> | <lopgate> | <terminate> | {<process>}

<andgate> ::= and(<something><something>)

<xorgate> ::= xor(<something><something>)

<seqgate> ::= seq(<something><something>)

<optgate> ::= opt(<something>)

<lopgate> ::= lop(<something>)

<terminate> ::= trm()

<process> ::= a | b | c | d